### ISSUE TITLE
Add python-dev to the image

### ISSUE THREAD

**Issue by mindlace** [aws/sagemaker-tensorflow-container#172] opened 2019-03-01 21:13 UTC
if a package in a `requirements.txt` requires complilation, it fails.

If the `python-dev` package were added to the image, then it would succeed.

Currently working around this as follows:

```python
import subprocess
try:
  import matplotlib
except ImportError:
  subprocess.call(["apt-get", "update"])
  subprocess.call(["apt-get", "install", "-y", "--allow-unauthenticated", "python-dev"])
  subprocess.call([sys.executable, "-m", "pip", "install", "matplotlib"])
  import matplotlib
```

Kind of complicated.

**Comment by iquintero** [comment] 2019-03-01 22:38
Hi @mindlace 

Thanks for reporting this, we were not aware of this regression. I will discuss this with the team to get your PR merged and potentially replicate it across our other containers.

**Comment by iquintero** [comment] 2019-03-01 23:36
I've merged your PR and it turns out our other containers are already using python-dev. Im going to close this issue feel free to reopen if you have any further comments :)

**Closed by iquintero** 2019-03-01 23:36 UTC
