### ISSUE TITLE
Tensorflow already installed in the Base image

### ISSUE THREAD

**Issue by PedroCardoso** [aws/sagemaker-tensorflow-container#55] opened 2018-07-11 16:55 UTC
In the current last version (1.8.0) Tensorflow is installed in the base docker image. It is one of the dependencies of the other packages. Currently it actually installs the latest version, so 1.9.0

Why do we need to give tensorflow package at build time for the final image ? Is there a reason not to just give the correct version on the base build time ?

**Comment by mvsusp** [comment] 2018-07-13 17:15
Hello @PedroCardoso,

You are correct that some dependencies might install TensorFlow in the base image. The final image installs (or in the case that you mentioned, overrides) an optimized TensorFlow binary instead of the original TensorFlow binary available in pypi:

https://github.com/aws/sagemaker-tensorflow-container/blob/master/docker/1.8.0/final/py2/Dockerfile.cpu#L14

I pulled both CPU and GPU 1.8.0 final images and tested the installed framework version. I can confirm that the final version installed in the container is the optimized 1.8.0. Please see picture below as an example on how I confirmed the version.

![screen shot 2018-07-13 at 10 14 41 am](https://user-images.githubusercontent.com/142074/42704665-9da9801a-8685-11e8-960d-11f747201898.png)


Best 

Márcio

**Comment by PedroCardoso** [comment] 2018-07-16 16:58
A good valid point.
On this, is there a place where I could download compiled versions of tensorflow with CPU and GPU, optimised for sagemaker, in a Wheel format ?

**Comment by andremoeller** [comment] 2018-07-20 06:32
Hi @PedroCardoso ,

We don't distribute these binaries. Since your original question was answered, I'm going to close this issue, but please feel free to reopen it if you have more questions. Thanks!

**Closed by andremoeller** 2018-07-20 06:32 UTC
Labels: question
